---
dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
description: "A new Flutter application."
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.1.0 <3.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/images/

name: flutter_layout_tutorial
version: 1.0.0+1
